// Game tag enums and related types
export {
  GameTag,
  Zone,
  PlayState,
  Step,
  CardType,
  Mulligan,
  State,
} from "./game-tags";

// Race/tribe enum and helpers
export { Race, BG_PLAYABLE_RACES, raceDisplayName } from "./races";

// BG hero card IDs
export {
  BG_HEROES,
  getHeroDisplayName,
  type BgHeroCardId,
} from "./card-ids";

// BG-specific constants
export {
  LOG_POLL_INTERVAL_MS,
  MAX_LOG_LINE_BUFFER,
  SIMULATION_ITERATIONS,
  SIMULATION_TIMEOUT_MS,
  SIMULATION_TIMEOUT_COMPLEX_MS,
  MAX_BOARD_SIZE,
  MAX_PLAYERS,
  MAX_TAVERN_TIER,
  HEARTHSTONE_WINDOW_NAMES,
  HEARTHSTONE_WINDOW_CLASS,
  DEFAULT_LOG_PATH,
  POWER_LOG_FILENAME,
  LOG_CONFIG_PATH,
  TAVERN_UPGRADE_COST,
  RECRUIT_PHASE_DURATION_SECONDS,
} from "./bg-constants";

// Log regex patterns
export {
  LOG_LINE_REGEX,
  GAME_MODE_REGEX,
  NEXT_GAME_MODE_REGEX,
  BLOCK_START_REGEX,
  BLOCK_END_REGEX,
  GAME_ENTITY_REGEX,
  PLAYER_ENTITY_REGEX,
  TAG_CHANGE_REGEX,
  FULL_ENTITY_REGEX,
  UPDATING_ENTITY_REGEX,
  HIDE_ENTITY_REGEX,
  CREATION_TAG_REGEX,
  ENTITY_REGEX,
  SHUFFLE_DECK_REGEX,
  CARD_ID_REGEX,
  SUB_SPELL_START_REGEX,
  META_INFO_REGEX,
  CHOICES_HEADER_REGEX,
  CHOSEN_HEADER_REGEX,
  CHOICES_SOURCE_REGEX,
  CHOICES_ENTITY_REGEX,
  END_TASK_LIST_REGEX,
  PLAYER_INFO_REGEX,
} from "./log-patterns";
