/**
 * Race enum ported from HearthDb.Enums.Race
 * https://github.com/HearthSim/HearthDb
 *
 * Represents minion tribes/races in Hearthstone.
 */
export enum Race {
  INVALID = 0,
  BLOODELF = 1,
  DRAENEI = 2,
  DWARF = 3,
  GNOME = 4,
  GOBLIN = 5,
  HUMAN = 6,
  NIGHTELF = 7,
  ORC = 8,
  TAUREN = 9,
  TROLL = 10,
  UNDEAD = 11,
  WORGEN = 12,
  GOBLIN2 = 13,
  MURLOC = 14,
  DEMON = 15,
  SCOURGE = 16,
  MECHANICAL = 17,
  ELEMENTAL = 18,
  OGRE = 19,
  BEAST = 20,
  TOTEM = 21,
  NERUBIAN = 22,
  PIRATE = 23,
  DRAGON = 24,
  ALL = 26,
  EGG = 38,
  QUILBOAR = 43,
  CENTAUR = 80,
  FURBOLG = 81,
  HIGHELF = 83,
  TREANT = 84,
  OWLKIN = 85,
  HALFORC = 88,
  LOCK = 89,
  NAGA = 92,
  OLDGOD = 93,
  PANDAREN = 94,
  GRONN = 95,
  CELESTIAL = 96,
  GNOLL = 97,
  GOLEM = 98,
  HARPY = 99,
  VULPERA = 100,
}

/**
 * Races that are playable in Battlegrounds.
 * These appear in the tavern pool and can be active/inactive per game.
 */
export const BG_PLAYABLE_RACES: Race[] = [
  Race.BEAST,
  Race.DEMON,
  Race.DRAGON,
  Race.ELEMENTAL,
  Race.MECHANICAL,
  Race.MURLOC,
  Race.NAGA,
  Race.PIRATE,
  Race.QUILBOAR,
  Race.UNDEAD,
] as const;

/**
 * Display names for races used in Battlegrounds.
 * Provides both Korean and English names.
 */
export const raceDisplayName: Record<Race, { en: string; ko: string }> = {
  [Race.INVALID]: { en: "No Type", ko: "종족 없음" },
  [Race.BLOODELF]: { en: "Blood Elf", ko: "블러드 엘프" },
  [Race.DRAENEI]: { en: "Draenei", ko: "드레나이" },
  [Race.DWARF]: { en: "Dwarf", ko: "드워프" },
  [Race.GNOME]: { en: "Gnome", ko: "노움" },
  [Race.GOBLIN]: { en: "Goblin", ko: "고블린" },
  [Race.HUMAN]: { en: "Human", ko: "인간" },
  [Race.NIGHTELF]: { en: "Night Elf", ko: "나이트 엘프" },
  [Race.ORC]: { en: "Orc", ko: "오크" },
  [Race.TAUREN]: { en: "Tauren", ko: "타우렌" },
  [Race.TROLL]: { en: "Troll", ko: "트롤" },
  [Race.UNDEAD]: { en: "Undead", ko: "언데드" },
  [Race.WORGEN]: { en: "Worgen", ko: "늑대인간" },
  [Race.GOBLIN2]: { en: "Goblin", ko: "고블린" },
  [Race.MURLOC]: { en: "Murloc", ko: "멀록" },
  [Race.DEMON]: { en: "Demon", ko: "악마" },
  [Race.SCOURGE]: { en: "Scourge", ko: "스컬지" },
  [Race.MECHANICAL]: { en: "Mech", ko: "기계" },
  [Race.ELEMENTAL]: { en: "Elemental", ko: "정령" },
  [Race.OGRE]: { en: "Ogre", ko: "오우거" },
  [Race.BEAST]: { en: "Beast", ko: "야수" },
  [Race.TOTEM]: { en: "Totem", ko: "토템" },
  [Race.NERUBIAN]: { en: "Nerubian", ko: "네루비안" },
  [Race.PIRATE]: { en: "Pirate", ko: "해적" },
  [Race.DRAGON]: { en: "Dragon", ko: "용" },
  [Race.ALL]: { en: "All", ko: "전체" },
  [Race.EGG]: { en: "Egg", ko: "알" },
  [Race.QUILBOAR]: { en: "Quilboar", ko: "퀼보어" },
  [Race.CENTAUR]: { en: "Centaur", ko: "켄타우로스" },
  [Race.FURBOLG]: { en: "Furbolg", ko: "펄볼그" },
  [Race.HIGHELF]: { en: "High Elf", ko: "하이 엘프" },
  [Race.TREANT]: { en: "Treant", ko: "고대정령" },
  [Race.OWLKIN]: { en: "Owlkin", ko: "올빼미족" },
  [Race.HALFORC]: { en: "Half-Orc", ko: "하프 오크" },
  [Race.LOCK]: { en: "Lock", ko: "자물쇠" },
  [Race.NAGA]: { en: "Naga", ko: "나가" },
  [Race.OLDGOD]: { en: "Old God", ko: "고대 신" },
  [Race.PANDAREN]: { en: "Pandaren", ko: "판다렌" },
  [Race.GRONN]: { en: "Gronn", ko: "그론" },
  [Race.CELESTIAL]: { en: "Celestial", ko: "천상의 존재" },
  [Race.GNOLL]: { en: "Gnoll", ko: "놀" },
  [Race.GOLEM]: { en: "Golem", ko: "골렘" },
  [Race.HARPY]: { en: "Harpy", ko: "하피" },
  [Race.VULPERA]: { en: "Vulpera", ko: "벌페라" },
};
